source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Animate_Example', :exclusive => true do
  pod "Animate", :path => "../"
end

target 'Animate_Tests', :exclusive => true do
  pod "Animate", :path => "../"

  pod 'FBSnapshotTestCase'
end
